In [1]:
import numpy as np

In [5]:
states = [0,1,2,3,4]
action = [0,1]
N_STATES = len(states)
N_ACTIONS = len(action)
P = np.zeros((N_STATES, N_ACTIONS, N_STATES)) # transition probability
R = np.zeros((N_STATES, N_ACTIONS, N_STATES)) # rewards

In [6]:
print(P)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [9]:
P[0,0,1] = 1.0
P[1,1,2] = 1.0
P[2,0,3] = 1.0
P[3,1,4] = 1.0
P[4,0,0] = 1.0
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [10]:
R[0,0,1] = 1
R[1,1,2] = 10
R[2,0,3] = 100
R[3,1,4] = 1000
R[4,0,0] = 1.0
print(R)

[[[   0.    1.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.   10.    0.    0.]]

 [[   0.    0.    0.  100.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0. 1000.]]

 [[   1.    0.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]]


In [13]:
gamma = 0.75

# initilize policy and value arbatrarily
policy = [0 for s in range (N_STATES)]
V = np.zeros(N_STATES)

print("Initial Policy", policy)
print(V)


Initial Policy [0, 0, 0, 0, 0]
[0. 0. 0. 0. 0.]


In [20]:
is_value_changed = True
iterations = 0
while is_value_changed:
    is_value_changed = False
    iterations += 1
    # run value iteration for each state
    for s in range(N_STATES):
        V[s] = sum([P[s,policy[s],s1] * (R[s,policy[s],s1] + gamma*V[s1]) for s1 in range(N_STATES)])
        # print "Run for state", s

    for s in range(N_STATES):
        q_best = V[s]
        # print "State", s, "q_best", q_best

    for a in range(N_ACTIONS):
        q_sa = sum([P[s, a, s1] * (R[s, a, s1] + gamma * V[s1]) for s1 in range(N_STATES)])
        if q_sa > q_best:
            print ("State", s, ": q_sa", q_sa, "q_best", q_best)
            policy[s] = a
            q_best = q_sa
            is_value_changed = True

    print ("Iterations:", iterations)
    # print "Policy now", policy

print ("Final policy")
print (policy)
print (V)

Iterations: 1
Final policy
[0, 1, 0, 1, 0]
[ 638.44814341  849.93085787 1119.9078105  1359.87708067  479.83610755]
